version: '3.8'

services:
  app:
    build: ./
    restart: always
    container_name: cep-service
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/cepdb;
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      REDIS_HOST: redis
    ports:
      - 8084:8080
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres:15.3-alpine
    container_name: postgressql
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db_start.sql:/docker-entrypoint-initdb.d/db_start.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8081:80
    volumes:
      - ./docker-compose/pgadmin:/var/lib/pgadmin

