management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      circuitViacep:
        slidingWindowType: COUNT_BASED
        registerHealthIndicator: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 60s
        permittedNumberOfCallsInHalfOpenState: 3


spring:
  application:
    name: cep-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS:PASSWORD:12345!}
  cache:
    type: redis
    cache-names: cep

  datasource:
    read:
      url: ${DB_READ_URL}
      username: ${DB_READ_USERNAME}
      password: ${DB_READ_PASSWORD}
      driverClassName: "org.postgresql.Driver"
    write:
      url: ${DB_WRITES_URL}
      username: ${DB_WRITES_USERNAME}
      password: ${DB_WRITES_PASSWORD}
      driverClassName: "org.postgresql.Driver"